### ISSUE TITLE
Allow passing extensions in the .remarkrc

### ISSUE THREAD

**Issue by remcohaszing** [remarkjs/ideas#10]
### Subject of the feature

It should be possible to specify the extension on which to run the CLI in the `.remarkrc` file.

### Problem

I would like to run remark-lint on my `.mdx` files.

### Expected behaviour

Extensions can be configured in `.remarkrc`. E.g.:

```js
exports.extensions = ['md', 'mdx'];

// or

exports.ext = ['md', 'mdx'];
```

### Alternatives

`ext` can be passed as a command line parameter.

```
remark --ext md,mdx .
```

**Comment by wooorm** [comment]
I think `--ext, --extension` should remain the only way to define extensions (you can also use globs btw).

We can’t store configuration on how to search in config files, because config files are detected after files are found. First files searched, then for each file the closest config file is found.

Adding extensions in config files would come with technical difficulties and a bunch of added complexity, I think the current alternative (`remark --ext md,mdx .`) is fine.
