### ISSUE TITLE
Support for Pandoc style citations

### ISSUE THREAD

**Issue by tchak** [remarkjs/ideas#18]
### Support for Pandoc style citations

A good description of format is here [https://pandoc.org/MANUAL.html#citations]()

I could not find any prior discussions of this. From my understanding it would require to extend `mdast`? Is it something that a plugin can do?

**Comment by wooorm** [comment]
Hi there Paul! Welcome!

Yes, this is something plugins can do, and remark leaves it up to userland (other folks) to add such extensions. That’s why I’ll close this issue here!

Similar plugins are [`remark-footnotes`](https://github.com/remarkjs/remark-footnotes) and [`remark-math`](https://github.com/remarkjs/remark-math)!
